

name: first yaml file

on:
 push:
  branches:
   - main

permissions:
  id-token: write       # Required to request the OIDC token
  contents: read        # Required to access the repository content


jobs:
  deploy:
    runs-on: ubuntu-latest  # Runner image

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      # Checks out your repository so the workflow can access the files

    - name: Azure Login using OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}           
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}           
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
        allow-no-subscriptions: true 
        
    - name: Create resource group # new rg created
      run: |
        az group create \
          --name my-github-action-rg \
          --location eastus  
          
    - name: Create storage account
      run: |
        az storage account create \
          --name mygithubstorage123 \
          --resource-group my-github-rg \
          --location eastus \
          --sku Standard_LRS \
          --kind StorageV2 \
          --access-tier Hot
     
        
   
